AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
  DisplayCopNames: true

Style/IndentationWidth:
  Enabled: false
Style/ElseAlignment:
  Enabled: false
Lint/EndAlignment:
  Enabled: false
Lint/RescueException:
  Enabled: false
Metrics/MethodLength:
  Max: 50
Metrics/ClassLength:
  Max: 150
Metrics/AbcSize:
  Max: 60
Metrics/BlockLength:
  Max: 50
Style/MultilineMethodCallIndentation:
  Enabled: false
