AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
  DisplayCopNames: true

Metrics/MethodLength:
  Max: 50
Metrics/ClassLength:
  Max: 150
Metrics/AbcSize:
  Max: 40
Metrics/BlockLength:
  Max: 50
Style/MultilineMethodCallIndentation:
  Enabled: false
