language: ruby
sudo: required
rvm:
  - 2.3.3
cache: bundler
branches:
  only:
    - master
addons:
  apt:
    packages:
      - libmagic1
      - libmagic-dev
install:
  - travis_retry bundle update
  - sudo add-apt-repository -y ppa:git-core/ppa
  - sudo apt-get update -y
  - sudo apt-get install -y git
script:
  - rake

