dynamodb:
  - key: test
  - secret: test

id_rsa: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpQIBAAKCAQEA1g0CFKoGHxfH1uk/xZWGNjbHoWvFGqat/WpycLq/TrCnjz7k
  R1SS6552hgeeFMutrqCLtAGXrIkkQy4w0CNAlY3cgckPb0MhF+paYPY4l9+ESidx
  PjQl8PW4jYRFoSANHczFd0XDNCFsQ2gWs2F4CPmGp6Z7KLET8F5tl0yZqD7BSWF8
  c1LVHG+oDEKt5FGjR7SFRoMGkqoVQFrD/F/vlhOrPRv1uV1gTq+beZRxXotsARn1
  DrASSjzmDZGZmWZgeUYBvq2UerwWcML12EBUenJ0lNrezK7yP6/W6lefnlfoMuBt
  vS/LKY76v0DiEnMoLCtlVQ78j3Osi4h5dVXLLQIDAQABAoIBACQnDEvrL59+x7zv
  plq713A+rlcAOck3j7l2ih+qGveydIqIJ8w4Z5wuJnyausNuZ0ZQTWg4wKJeg2Zp
  Xcs5uQXJcQ3mpJm5L9S3O06XJ5XXJaPUp5bG/gWFqwcT6SK+pBh9ZnivqrmaT4vO
  /86KTtjNNEYKo1CLIAAAIuhkAqvcpmNfiSDmNvdWUwSU3WZJLX3YBmDW4FO32ql+
  7T3fB+LQvm+HnbVl6bpq/jwHP6+hevcWsBZKWhrzl6zbMW/aPWBzfz9kmqzV3Mxh
  GhtyiU21xb6WavMi2WsaEbUKtUfJiBFiDUV0T7aRgpoMqhJvLHOMepRGEDJfzdXk
  vyyQVe0CgYEA9dV3M+Rxr+mM2AdDYmffc1VfuyrCrM/42vjKwuysA6XUCgpRiTPt
  QzgRtUby6rMz7b/VekBLDh7KX1ObCEQtwczaAl+BisfuHgvmiwSDDNcEk/JL5qQ3
  gbbKyrFqNWecs/U7/IbC9eCpW5wlqO2CdBfhawbKuaxEB0+W0HAkfH8CgYEA3ucR
  zAdd2kx1XUMk2sgVT9DmWYybwkK5CTe6xfOkhjQXLHGUwyJMZs/IgiWlKeg1vHSG
  wm7eAtJAQWEcGNwh214dUwD/6KONDzcj0wElrw8/ooF7b+xitFKyAmnm9G+y82p7
  7jqe8me+fFcXVcA8nG0T4RRFUHQI2wNQY7j/klMCgYEA4hxYirNI2gtPz3dGxGFU
  Bmn1JlsbOgYEF6wUGxvCz4wcLqv0+OR5C4Wry/eZAMSZM8lpWgt+vVsWun1UsFK9
  X27C6sHbjcF8w8ggYadhvlKa1FVc+KP8peNyPOLYFIzbdi5O4WM2OR9NxoQlo23p
  ukwout9BYWwQGkVbKxaqiJMCgYEAko9WCVPypr1NEfQ7AEs8kA1n2At2woUCiwgE
  m3F2hPMtJYDM8nzTxWnriX9dGK/g3Te0/5TMDwjVTOegBMyAym8YUuI+YWVgM1fr
  Cyse7vrUuXHviojf4XbaKnIddC0ZealTMTGEHxiNi83rvus2LxgdUQn2BU82H2MP
  cXJLQJcCgYEAjJmGojXWhCeRnZEb0aAt0RRflN0TeQ1/mttRA3Twdb07XS8Kqy3c
  bp9muU/NU8TRWckC7ZjaZe60A4UfZNbIzbz19CO6ZJNuDBTynobyv6KN4RKucjDV
  Y0y5TY5hKfznPK1qJZERHJTJg+EjZkK/ptQt20ePhSl8bO/BBLY3ft8=
  -----END RSA PRIVATE KEY-----
