s3:
  region: us-east-1
  bucket: xml.0pdd.com
  key: AKIAINXYBLMBAI4DFWFA
  secret: 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
sentry: https://e958648dae2540ebab6975edd2e88086:4745b8323ffc40f2bb314c98565b98d4@sentry.io/194178
dynamo:
  region: us-east-1
  key: AKIAINXYBLMBAI4DFWFA
  secret: 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
github:
  login: 0pdd
  pwd: Tiug7gY5
smtp:
  host: email-smtp.us-east-1.amazonaws.com
  port: 587
  user: AKIAIPMIS45U6UG2TZCQ
  password: ArPxO8SD56yoyG8cKM80IYvMQve8Wss+L4kinJZUUGct
id_rsa: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpQIBAAKCAQEApSEiXNICn1VNt3N/U+za15NdO4e2bln/1YeTExZYrwIgwoLh
  W37CDI8bMEmZSXFGg8/f4tzOH7Mov2J5nqFyWBHQvNY7Ss/FJW1JgH858Fd1bpPj
  0sTpsTmDYvgbhPz6510FyZZeqOll9+Q50ZjAdrP9wce+QrP3RkBLjj70pQ0i1xO+
  fuAeoE+GSs6bRqut81n/HcNYOrSFy2FoDqDqs8PvlcB8LKtaFITICWPBhh2TvjqR
  YTD3nekZB2YQKQsL8zt8mz6aX2c1ESI29diOtn4CxSdfEuxbUTwqgOCcM/QEDC7V
  OOjNQXVUXiH3ArdiVoWbtE6Iqp3Jx8662nx68wIDAQABAoIBADvfxsjnMSI62QIi
  s9FneXZfLZgPPlvG8FepX++005UpbV15/WKilJPfM9mPZjBWDV5v+lsU+vxNhwHW
  IAkfuwkp9Ij0GO2oZnCKrvMTrptx6teccigTVDT5iKVTFw9id0t61EVi65HNhzaa
  H0jbXTXtT5564YboIEntuDespiJOCs2s0sseKpJ/09Ltq+8iAnU29KzwsXVUykWw
  r3qqIhQiZ5kTxHp9pxabI5GrUMvWjve2qcGB17qCvzLerTQhzAfVRl6aDsy+PQsv
  mdiepMXGyyqZmcbrGEIaVAzePw3+DKPwe40tWZ19YNDzG3UttPLVxfS9slSSsFyO
  coMRHnECgYEA1p9KvPHDbMt4trdUL4vWOI7FErVClGf/GZDmS30Gaexi8hkUT/Li
  w14WJxoHHMQaiUUBhRFJav2/3WDUJBIl9JWS+1gqJRggPTsotKx2o93vP0jCSkdO
  cC9V8GaPj3Bi/1uiGK1M9u9Id6ipVM6uBjwp8ux6AgFBAkAIRy06UJsCgYEAxPce
  Wxu0Ye5o9yBn6gkA8WjrN39cA4YcD9gn3c0bdY+qjSw56ydZdV4D6K+C4gXFQnKG
  pu+WQ5zkRyDKpv4/Ax3TGXGHWS84eEoD1wZsNlFAuWisAcZ9guEln+10VRo2h1Wl
  OqiJEqFYscOS79+20LckKKayLkbMsMkrcA0viIkCgYEAh7Bp9g77uNrjVNGPPggw
  xc0tt2g10dH2LFm539wJpAo5fEpy1yD+UPo5EzuXZ45sIIEqNtD5E9Wd6f5/4NZA
  fOPb62CQNKeOKmgukhu/XlbAHciIXaG7a53hvX16Ifux+zQZxXQ7hps9u7k8ZUvO
  Jk7/ToBHmuDkEuIc2bM0fSUCgYEAstGT+q01X++d1jbSgLR56bISUolLFVvtIClj
  UEhFVL8A3Tg4wRgxbI/VRqwJTIBmrUPioa5Eos/OpBDOSzvqIz8xhxj+A2cOgo7X
  26DWH542/91axCXbjzYu/XoMMrMgrE+CObYG9CYNqx3eye42QFj09/8XJ1JZxWpu
  CEXAUNkCgYEAlRE6tCAI3EGa8oxp+qcTKyxYFs/2wyJEkWJu6I2u8JDXexy7LSoo
  ypE/ILCXf2Y8xJP2hLGcArBsYqDuKbg7drLtu7Sk0lABFkVll8eUcKmoBvSIFXdj
  xwwn1PBDJmUrwUWcevG41zV/fOga7CQSumlUP2AbO3tIeCn7fBbbf90=
  -----END RSA PRIVATE KEY-----
